# Generated by Django 6.0.1 on 2026-01-11 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='Currency',
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('gold', 'Gold'), ('platinum', 'Platinum')], max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceduration',
            name='duration',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceduration',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='durations', to='website.service'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=models.ImageField(upload_to='service_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('TSH', 'TSH'), ('KSH', 'KSH'), ('UGX', 'UGX')], default='USD', max_length=10),
        ),
    ]
