# Generated by Django 6.0.1 on 2026-01-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_order_duration_service_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='order_documents/'),
        ),
        migrations.AddField(
            model_name='order',
            name='duration',
            field=models.CharField(default='2 days', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
