# Generated by Django 6.0.1 on 2026-01-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_order_document_remove_order_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='currency',
        ),
        migrations.AddField(
            model_name='order',
            name='contact_phone',
            field=models.CharField(default='+255742461917', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='order_documents/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
